# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac66ffb66689b0100f2064e4fa2260d5006564cce00981126fe5f93fa71169a12133ac1c19320a798f75659531d1c07a8914743c714e4ada2ab66e66a1528cbb

test:
  secret_key_base: 594068cd51aa2ed1fe9e5f1326ef9961040daf9bb64444da9419a254f462a8d191ddf72fc896b9d52905851f8f204625501b3dff3a0770e9710ad7f7cea2020e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
